### ISSUE TITLE
Diffusers_Or_Repo_Choice

### ISSUE THREAD

**Issue by ioritree** [smthemex/ComfyUI_HiDiffusion_Pro#1]
貌似沒有local_model_path的節點
只有指向diffusers跟目錄的節點

**Comment by smthemex** [comment]
对的，这个节点只是指向diffusers目录，而且对该目录有文件过滤，只匹配有model_index.json的所有标准扩散模型，以及cannyXL，mistoline，inpaintingXL，所以要使用这个菜单，diffusers目录需要有含VAE、unet，encoder等等的标准文件结构的扩散模型。当然，如果你不想哟个菜单，在repo_id填写对应的repo_id，或则该扩散模型的绝对地址也一样使用。 节点连接的repo_id，可以参考我的示例图片。

**Comment by Omarsmsm** [comment]
Can we edit the files for other unsupported models to make them work. Like Corcelio/mobius

**Comment by smthemex** [comment]
you can try edit model.yaml， and add your repo  behind  surport_model or sdxl_model（if your repo base sdxl）

**Comment by ioritree** [comment]
作者的插件很不錯，只是每個插件會自己下載所需的擴散模型文件，一下載就是10~30G不等,硬盤很快就見紅了

**Comment by smthemex** [comment]
所以我一般建议用我另一个pipeline工具 预下载模型到comfyUI的diffusers目录位置，这样避免C盘爆掉。或者你可以更改hub的cache目录至其他盘
